[workspace]
members = ["crates/*"]

[workspace.package]
# KEEP IN SYNC WITH python/pyproject.toml
version = "0.5.0"
edition = "2021"
rust-version = "1.69"
homepage = "https://github.com/NickCrews/feco3"
repository = "https://github.com/NickCrews/feco3"
