from __future__ import annotations
from dataclasses import dataclass
from functools import cached_property

import os

import _feco3


def parse(fec_path: str | os.PathLike, out_dir: str | os.PathLike) -> None:
    """Parse a FEC file and output the results to a directory.

    Args:
        fec_path: The path to the FEC file to parse.
        out_dir: The directory to output the results to.
    """
    _feco3.parse_from_path(fec_path, out_dir)


class FecFile:

    def __init__(self, src: str | os.PathLike) -> None:
        """Create a new FecFile instance.

        Args:
            src: The path to the FEC file to parse.
        """
        # An instance of _feco3.FecFile, which is the class generated by pyo3
        self._src = src
        self._wrapped = _feco3.FecFile.from_path(src)

    @cached_property
    def header(self) -> Header:
        h = self._wrapped.header
        return Header(
            fec_version=h.fec_version,
            software_name=h.software_name,
            software_version=h.software_version,
            report_id=h.report_id,
            report_number=h.report_number,
        )


    def __repr__(self) -> str:
        src_str = f"src={self._src!r}"
        return f"{self.__class__.__name__}({src_str})"


@dataclass
class Header:
    fec_version: str
    software_name: str
    software_version: str | None
    report_id: str | None
    report_number: str | None


class ParquetProcessor:

    def __init__(self, out_dir: str | os.PathLike) -> None:
        self._wrapped = _feco3.ParquetProcessor(out_dir)

    def process(self, fec_file: FecFile) -> None:
        self._wrapped.process(fec_file._wrapped)
