site_name: feco3
repo_url: https://github.com/NickCrews/feco3
theme:
  name: material
plugins:
  - search
  - literate-nav
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://arrow.apache.org/docs/objects.inv
          options:
            show_source: false
            separate_signature: true
            show_signature_annotations: true
            show_root_full_path: false
            show_root_heading: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
